pipeline {
    agent any

    tools {
       
        maven "maven3.8.1"
    }

    stages {
        stage('Build') {
            steps {
                
                git 'https://github.com/sahithi283/MyWebProject.git'

                
                sh "mvn -f artifactid/pom.xml clean"
             
            }

        }
        stage('Test') {
            steps {
        
                git 'https://github.com/sahithi283/MyWebProject.git'

                
                sh "mvn -f artifactid/pom.xml test"
             
            }

        }
        
        stage('Package') {
            steps {
        
                git 'https://github.com/sahithi283/MyWebProject.git'

                
                sh "mvn -f artifactid/pom.xml package"
             
            }

        }
        
        stage('Upload the binary artifact to nexus'){
            steps{
                nexusPublisher nexusInstanceId: 'nexus1', nexusRepositoryId: 'JenkinsCICDRepository', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: 'artifactid/target/artifactid.war']], mavenCoordinate: [artifactId: 'mycompany', groupId: 'com', packaging: 'war', version: '3.0']]]
            }
        }

        stage('Upload binary file to tomcat'){
		steps{
			sh "wget --user=admin --password=admin http://18.222.129.177:8081/repository/JenkinsCICDRepository/com/mycompany/3.0/mycompany-3.0.war"
		}
	}
        
        stage('Deploy'){
            steps{
                deploy adapters: [tomcat9(credentialsId: 'TomcatCredentials', path: '', url: 'http://3.21.227.42:8090/')], contextPath: null, war: '**/*.war'
            }
        }
        
    }

}
